stages:
  - test
  - tag

variables:
  GIT_STRATEGY: clone

before_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup

after_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup

test-template:
  stage: test
  hooks:
    pre_get_sources_script:
    - sudo chown gitlab-runner -R ${CI_PROJECT_DIR}
  script:
    - mkdir reports
    - docker build -f dockerfiles/Dockerfile -t image .
    - docker run -u `id -u`:`id -g` image poetry run ruff check
    - docker run -u `id -u`:`id -g` image poetry run ruff format --check
    - docker run -u `id -u`:`id -g` image poetry run mypy .
    - docker run -u `id -u`:`id -g` -v `pwd`/reports:/src/reports image poetry run coverage run
    - docker run -u `id -u`:`id -g` -v `pwd`/reports:/src/reports image poetry run coverage xml -o reports/coverage.xml
    - sed -i "s:<source>/src:<source>${CI_BUILDS_DIR}/${CI_PROJECT_PATH}:" reports/coverage.xml

  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage.xml
  tags:
    - rse-multi-builder


tag-release:
  stage: tag
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never
  script:
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - chmod +x scripts/bump_tag.sh
    - NEW_TAG=$(scripts/bump_tag.sh)
    - git remote add gitlab https://oauth2:${NDIP_GROUP_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git tag ${NEW_TAG}
    - git push gitlab --tags
  tags:
    - rse-multi-builder