ARG SOURCE_IMAGE=source

FROM --platform=amd64 regproxy.ornl.gov/hub_proxy/python:3.10-slim AS source

# make sure image can run as non-root user
ENV POETRY_CACHE_DIR=/poetry/.cache
ENV POETRY_CONFIG_DIR=/poetry/.config
ENV POETRY_HOME=/poetry

RUN pip install poetry
COPY . /src
WORKDIR /src

RUN poetry install
RUN poetry build --format=wheel

RUN chmod og+rwX -R /poetry
RUN chmod og+rwX -R /src


# This is a workaround that allows the COPY --from location to be defined as a build argument.
# With this, we can reference the built source image from Harbor in our pipelines, while still
# defaulting to using the previous stage for local builds.
FROM $SOURCE_IMAGE as source_image


{% if use_mantid -%}
FROM --platform=amd64 regproxy.ornl.gov/hub_proxy/kitware/trame:py3.10-conda-2024-11 AS run

RUN conda create --yes -n {{ python_package }} -c conda-forge -c mantid python=3.10 mantid
SHELL ["conda", "run", "-n", "{{ python_package }}", "/bin/bash", "-c"]
ENTRYPOINT [ "conda", "run", "--no-capture-output", "-n", "{{ python_package }}" ]
{%- else %}
FROM --platform=amd64 regproxy.ornl.gov/hub_proxy/ubuntu:22.04 AS run

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata
RUN apt-get install -y python3.10 curl
RUN curl -ksS https://bootstrap.pypa.io/get-pip.py | python3.10
{%- endif %}

COPY --from=source_image /src/dist /dist
RUN pip install /dist/*.whl

{% if application_type in ['Nova Application', 'Tutorial'] and framework == 'Trame' -%}
RUN pip install supervisor

RUN apt update && apt install -y gettext nginx wget
RUN chmod og+rwX -R /var/lib/nginx
RUN chmod og+rwX -R /var/log/nginx
RUN chmod og+rwX -R /etc/nginx

COPY dockerfiles/nginx.conf.template /etc/nginx/nginx.conf.template
COPY dockerfiles/supervisord.conf /etc/supervisord.conf
COPY scripts/run_nginx.sh /
COPY scripts/run_trame.sh /

RUN python3.10 -m trame.tools.www --client-type vue3 --output /app/www-content

# Get the static JS from nova-trame and add it to our client build
RUN mkdir -p /app/www-content/assets/js
RUN export NOVA_TRAME_LOCATION=$(pip show nova-trame | grep "Location" | awk '{ print $2 }')/nova/trame; cp $NOVA_TRAME_LOCATION/view/theme/assets/js/*.js /app/www-content/assets/js/

CMD [ "supervisord" ]
{%- endif -%}
